### ISSUE TITLE
module parse failed

### ISSUE THREAD

**Issue by seeden** [react-component/tooltip#1]
I am not able to use this module because:

```sh
ERROR in ./~/rc-tooltip/lib/Tooltip.jsx
Module parse failed: \node_modules\rc-tooltip\lib\Tooltip.jsx
Line 12: Unexpected reserved word
You may need an appropriate loader to handle this file type.
| var Popup = require('./Popup');
|
| class Tooltip extends React.Component {
|   constructor(props) {
|     super(props);
 @ ./~/rc-tooltip/index.js 1:17-41
^C
D:\git\>node -v
v0.12.0
```
 
I guess that the main problem is that it is written in ES6 without conversion to ES5

**Comment by yiminghe** [comment]
add loader for jsx:

https://github.com/yiminghe/learning-react/blob/master/webpack.common.config.js#L37

**Comment by seeden** [comment]
I am using babel-loader for ES6 files except node_modules because speed. 

{ test: /\.jsx$/, exclude: /node_modules/, loader: 'babel-loader' },

**Comment by yiminghe** [comment]
it's no need to exclude node_modules, in my experience speed impact is little

**Comment by yiminghe** [comment]
1.1.2 npm install will install es5 code
