### ISSUE TITLE
Disable alignment so the tooltip always renders at defined placement (even if doesn't fit the viewpoint)

### ISSUE THREAD

**Issue by monkey3310** [react-component/tooltip#101]
Is there a way to disable automatic alignment so tooltip would render on desired `placement`, ignoring if it actually visible or not? 
We have a case that we show the tooltip on page render, and its attached to element that's not visible in the view on the render, so tooltip renders in incorrect place

**Comment by benjycui** [comment]
> its attached to element that's not visible

You mean that you set the element to `display: none`?

**Comment by monkey3310** [comment]
@benjycui sorry, that's not what I've meant - my scenario is as follows - tooltip is attached to element that is `visible` by the CSS terms, by visible I've meant its not in current viewport - user has to actually scroll to see it. But still, tooltip renders in the current viewport, (so about 200px) above actual point that I want it to attach to.

**Comment by benjycui** [comment]
Just upgrade to the latest rc-tooltip
