### ISSUE TITLE
React v16 Upgrade: Uncaught TypeError: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by pts-moog16** [react-component/tooltip#106]
I've been going through the process of upgrading to React v16. I'm getting an error:

![screen shot 2017-10-17 at 14 18 46](https://user-images.githubusercontent.com/23342596/31689982-20b38578-b346-11e7-873d-c129c0c8b41e.png)

I believe this is coming from your dependency on rc-trigger, which is set as `1.x` in package.json. It looks like they have update to use ES6 Component syntax and the prop-types lib. Can we upgrade this lib?

**Comment by primozs** [comment]
This module needs rc-trigger dependency upgrade

**Comment by pts-moog16** [comment]
related: https://github.com/react-component/slider/issues/339

**Comment by moog16** [comment]
Looks like this is open: https://github.com/react-component/tooltip/pull/105

**Comment by paranoidjk** [comment]
Release `rc-tooltip@3.6.0`. Please give it a try.

**Comment by pts-moog16** [comment]
Worked! thanks @paranoidjk
