### ISSUE TITLE
Provide color to rc-tooltip-inner by props.

### ISSUE THREAD

**Issue by Rahulkr204** [react-component/tooltip#107]
I want to use tooltip with different colors at different places in project. Any help is appreciated.

**Comment by yesmeck** [comment]
Use `overlayStyle`.

**Comment by abhijit154** [comment]
@yesmeck can you please give some example?? I have tried that but its not working

**Comment by yesmeck** [comment]
You can override style of `.rc-tooltip-inner` by css. https://codesandbox.io/s/1wn58vr98j

**Comment by jincan39** [comment]
it's globally?

**Comment by Cignite** [comment]
How can i change background using custom className props

```
<Tooltip
          visible={true}
          animation="zoom"
          onVisibleChange={this.onVisibleChange}
          trigger="click"
          overlay={<span>i am a tooltip</span>}
          className={styles.tooltip}
        >
          <span>trigger</a>
  </Tooltip>
```

```
.tooltip {
     width: 200px;
    background-color: #dedede;
}
```

**Comment by PatrickYoung03** [comment]
is there a way of removing or customising the arrow / inner arrow of this component
