### ISSUE TITLE
click 触发方式，点击其他地方浮层消失的行为

### ISSUE THREAD

**Issue by afc163** [react-component/tooltip#11]
目前的实现方式是用了一个透明的全局遮罩，这样会导致一旦点开了浮层，页面上其他地方的 mouseover 交互全部失效，点击交互需要点两次才能触发。

可以换一个更无痛的实现方式：

https://github.com/littlebits/react-popover/blob/a2f90b90c6498fb91c315201f679846c5701c9a1/lib/index.js#L382

**Comment by yiminghe** [comment]
2.2.0 改成这样的，这样能够使用 react 的事件，好像是不太好
