### ISSUE TITLE
Hide Tooltip `onClick`

### ISSUE THREAD

**Issue by chapati23** [react-component/tooltip#110]
Hi,
UX-wise, especially on mobile, I'd like users to be able to close tooltips by tapping on them. Or at least I'd want to show a little `X` on the top right of a tooltip and make the tooltip close when pressing that `X`. Tapping outside of a things isn't really an intuitive way to close it IMHO (other than a fullscreen modal). I couldn't figure out a way to close your tooltip `onClick` unfortunately.

Any reason you're not supporting an `onClick` handler on the tooltip itself?

**Comment by yesmeck** [comment]
You can bind onClick to the overlay.

```javascript
<Tooltip overlay={<div onClick={handleClick}>foo</div>} />
```

**Comment by chapati23** [comment]
Yes, that works. IMHO, an `onClick` prop on the tooltip component itself would be cleaner but that’s just my opinion :)
