### ISSUE TITLE
auto-position according to inner child position

### ISSUE THREAD

**Issue by AlonBe** [react-component/tooltip#112]
Hi there,

I'm trying to set a tooltip on component which changes his own position.
Apparently, the tooltip does not align itself to the component's position after it has been changed

The tooltip code:
```
render(){
    const alignObject = {
        overflow: { adjustX: true, adjustY: true }
    };
    return (
        <RcTooltip overlay={() => <span>does not matter</span>}
            placement={'bottomLeft'}
            align={alignObject}
            visible
        >
            <ComponentWithChangedPosition />
        </RcTooltip>
    );
}
```

and the child component (`ComponentWithChangedPosition`) is:
```
render(){
    // these values are changed during the application life cycle
    const { top, left } = this.state;
		
    return (
        <div style={{position: "absolute", top, left}} />
    );
}
```

what happens is that the child component changes his position according to its state, but the tooltip does not.

The only workaround I found is sending a prop "onUpdate" to the child component which is called after its position was update (`setState` second argument)

so currently, the workaround is:
```
render(){
    const alignObject = {
        overflow: { adjustX: true, adjustY: true }
    },
        // calling setState just to make rc-tooltip to be re-rendered after child was re-positioned
        onUpdate = () => this.setState({});

    return (
        <RcTooltip overlay={() => <span>does not matter</span>}
            placement={'bottomLeft'}
            align={alignObject}
            visible
        >
            <ComponentWithChangedPosition onUpdate={onUpdate} />
        </RcTooltip>
    );
}
```

any suggestions how to solve this issue without this workaround?

**Comment by benjycui** [comment]
Try getTooltipContainer.

**Comment by AlonBe** [comment]
Hi @benjycui,

I managed to solve my issue using "getTooltipContainer":
```
render(){
    const alignObject = {
        overflow: { adjustX: true, adjustY: true }
    };

    return (
            <Tooltip
                overlay={'does not matter'}
                getTooltipContainer={() => ReactDOM.findDOMNode(this.myRef)}
                placement={'bottomLeft'}
                align={alignObject}
                hideArrow
                visible
            >
                <ComponentWithChangedPosition ref={(e) => this.myRef = e} />
            </Tooltip>
    );
}
```

But the problem now is that the tooltip doesn't adjust itself to the screen's edges.
Meaning, that if the tooltip is out of the screen width\height - I get the browser's scrollbars instead of re-adjustment as happened with my workaround..

It will be highly appreciated to have a working example please

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://u.ant.design/codesandbox-repro
