### ISSUE TITLE
Tooltip blinking

### ISSUE THREAD

**Issue by juraj98** [react-component/tooltip#115]
You can see an example of this at https://codesandbox.io/s/n08njk0nm. This blinking is caused by the `div` appearing in front of the tooltip and cancelling the hover.

Although this could be avoided by setting the `z-index` on the `Item`, it is not the right solution for us, as it requires changing the `z-index` of every component to which we want to add the tooltip, which could cause unexpected issues with layouts.

**Comment by yesmeck** [comment]
You'd have to import 'rc-tooltip/assets/bootstrap.css', or write your own.
