### ISSUE TITLE
Delay in hiding tooltip when scrolling

### ISSUE THREAD

**Issue by denchen** [react-component/tooltip#118]
Is there any way of hiding a tooltip immediately when scrolling away from the trigger?

For example, on the examples page:
http://react-component.github.io/tooltip/examples/arrowContent.html

If I hover over an element to show the tooltip, and then scroll away without moving the cursor, the tooltip doesn't actually disappear until I stop scrolling, even though the cursor had already left the trigger area. So I could scroll really slowly and keep the tooltip up until the moment I stop.

**Comment by benjycui** [comment]
Just try `getTooltipContainer`, so that your tooltip will move with the moving target.

**Comment by denchen** [comment]
I actually do use `getTooltipContainer`, and it works as expected in that yes, the tooltip does move with the target. But the tooltip doesn't disappear even though my cursor is well away from the target, until I stop scrolling. So it's this that I want to eliminate. I want the tooltip to disappear immediately when the cursor moves away from the target, either by moving the mouse *or* by scrolling.

**Comment by benjycui** [comment]
So, just listen to `window.onScrol` to hide tooltip with `visible`.
