### ISSUE TITLE
Import issues 

### ISSUE THREAD

**Issue by MaximeHeckel** [react-component/tooltip#120]
Not sure if related to my recent update of my project or not but, after updating to webpack 4.5 I got the following message
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in. Check the render method of `Tooltip`.

`Tooltip` is just my component importing rc-tooltip and rendering it nothing fancy:
```
import RCTooltip from 'rc-tooltip';

export default class Tooltip extends React.Component {
  render() {
    <RCTooltip>
      {this.props.children}
    </RCTooltip>
  }
}
```

In order to get around this I had to do the following:

```
  render() {
    <RCTooltip.default>
      {this.props.children}
    </RCTooltip.default>
  }
```

Not sure what happened here, but I thought this was worth mentioning here

**Comment by MaximeHeckel** [comment]
I think this is why https://medium.com/webpack/webpack-4-import-and-commonjs-d619d626b655?source=linkShare-25ade300ab5-1523129422

**Comment by yesmeck** [comment]
Can not reproduce your issue with webpack 4, could you create a reproduction repo?

**Comment by mquandalle** [comment]
I created a minimal reproduction here: https://github.com/mquandalle/rc-tooltip-issue-120 @MaximeHeckel can you confirm that this is the same issue than yours?

**Comment by MaximeHeckel** [comment]
Seems related @mquandalle , going to bootstrap a small project and try to reproduce with webpack 4

**Comment by yesmeck** [comment]
@mquandalle 

`import * as Tooltip from "antd/lib/tooltip";` works, it seems it's a issue of fuse or TypeScript configuration.

**Comment by cronco** [comment]
I am also affected by this

**Comment by mquandalle** [comment]
@yesmeck In my main app I'm also experiencing the issue with `import * as Tooltip from "antd/lib/tooltip";` but I can't reproduce it in my minimal example, so I guess I'm missing something.

Is there any difference in the way this package is exported compared to other `rc` components?

**Comment by yesmeck** [comment]
All components of antd use the same exports:

https://unpkg.com/antd@3.4.1/lib/tooltip/index.js

<img width="328" alt="screen shot 2018-04-18 at 20 31 07" src="https://user-images.githubusercontent.com/465125/38931981-7c292854-4347-11e8-9542-f41d62882ea1.png">

https://unpkg.com/antd@3.4.1/lib/popover/index.js
<img width="347" alt="screen shot 2018-04-18 at 20 31 13" src="https://user-images.githubusercontent.com/465125/38931983-7ddabb5e-4347-11e8-8dea-04e432d2301c.png">

**Comment by yesmeck** [comment]
If you can import popover, but you can not import tooltip, if think it's a bug of FuseBox.

**Comment by mjrussell** [comment]
Same issue, this worked for me even with `concatenateModules: true` in my webpack config:
`import RCTooltip from 'rc-tooltip/es/index';`

**Comment by MaximeHeckel** [comment]
Updating this since I finally found the underlying issue. I was working on some not fully updated UI projects. One cause was that we had a bunch of ES5 modules in our code base and that we were using the `es2015` babel preset. Removing this and disabling modules helped us to finally fixed this issue.

Our `.babelrc`:

```
{
  "env": {
    "development": {
      "presets": [
        [
          "env",
          {
            "modules": false,
          }
        ],
        "react",
        "stage-0"
      ],
      "plugins": [
        "emotion",
        "transform-object-rest-spread",
        "transform-decorators-legacy",
        "transform-runtime",
      ]
    },
    "production": {
      "presets": [
        [
          "env",
          {
            "modules": false,
          }
        ],
        "react",
        "stage-0"
      ],
      "plugins": [
        "emotion",
        "transform-object-rest-spread",
        "transform-decorators-legacy",
        "transform-runtime",
      ]
    },
    "test": {
      "presets": [
        [
          "env",
          {
            "modules": false,
          }
        ],
        "es2015",
        "react",
        "stage-0"
      ],
      "plugins": [
        "emotion",
        "transform-object-rest-spread",
        "transform-decorators-legacy",
        "transform-runtime",
      ]
    }
  }
}
```
