### ISSUE TITLE
Tooltip have wrong placement for react-d3-tree 

### ISSUE THREAD

**Issue by aiportal** [react-component/tooltip#126]
simple demo is here: https://codesandbox.io/s/32o2m49qj5

`
import React from "react";
import Tooltip from "rc-tooltip";

type Props = {
  nodeData: Object
};

export default class NodeLabel extends React.PureComponent {
  props: Props;

  render() {
    const { nodeData } = this.props;

    return (
      <div>
        <Tooltip overlay={<span>tooltip</span>}>
          <h2>{nodeData.name}</h2>
        </Tooltip>
      </div>
    );
  }
}
`

`
import React from "react";
import { render } from "react-dom";
import "rc-tooltip/assets/bootstrap.css";
import Tree from "react-d3-tree";
import TreeNode from "./tree-node";

const myTreeData = [
  {
    name: "Top Level",
    attributes: {
      keyA: "val A",
      keyB: "val B",
      keyC: "val C"
    },
    children: [
      {
        name: "Level 2: A",
        attributes: {
          keyA: "val A",
          keyB: "val B",
          keyC: "val C"
        }
      },
      {
        name: "Level 2: B"
      }
    ]
  }
];

const App = () => (
  <div style={{ marginTop: 120 }}>
    <Tree
      data={Array.from(myTreeData)}
      translate={{ x: 50, y: 60 }}
      collapsible={false}
      transitionDuration={0}
      separation={{ siblings: 0.58, nonSiblings: 1 }}
      allowForeignObjects
      nodeLabelComponent={{
        render: <TreeNode />,
        foreignObjectWrapper: {
          x: -30,
          y: -12
        }
      }}
    />
  </div>
);

render(<App />, document.body.appendChild(document.createElement("div")));
`

**Comment by yesmeck** [comment]
https://codesandbox.io/s/548v1y7von

要引入 css

**Comment by aiportal** [comment]
@yesmeck 

引用了 css，还是没效果。

tree-node.jsx    文件如下：

`import React from "react";
import Tooltip from "rc-tooltip";
import "rc-tooltip/assets/bootstrap.css";


type Props = {
  nodeData: Object
};

export default class NodeLabel extends React.PureComponent {
  props: Props;

  render() {
    const { nodeData } = this.props;

    return (
      <div>
        <Tooltip overlay={<span>tooltip</span>}>
          <h2>{nodeData.name}</h2>
        </Tooltip>
      </div>
    );
  }
}
`
