### ISSUE TITLE
Tooltip always shown

### ISSUE THREAD

**Issue by alxhotel** [react-component/tooltip#127]
The tooltip is always visible even when it has the `trigger`.

Example code:

```js
showTooltip() {
    return <Tooltip
                trigger={["hover"]}
                placement="bottom"
                overlay={"Text here"}>
               Hello
            </Tooltip>
}

render () {
    return {
        <div>{showTooltip()}</div>
    }
}
```

**Comment by yesmeck** [comment]
`trigger` should be an element.

**Comment by alxhotel** [comment]
Hi @yesmeck, thanks for the quick response.

I have updated my question.

**Comment by alxhotel** [comment]
Here is an example: https://codesandbox.io/s/jzn0j61x0v

If you click the button, I expect to see the "Only on hover" text shown only when I hover. Instead I see it always.

**Comment by yesmeck** [comment]
Your link doesn't have a reproduction.

**Comment by alxhotel** [comment]
Sorry about that, try again.

**Comment by yesmeck** [comment]
https://codesandbox.io/s/0019m2mnon

**Comment by alxhotel** [comment]
Thanks, but that is not what I want.

I want to have in one case always visible and in another case only visible when hover over the text.

**Comment by yesmeck** [comment]
Plz ask usage questions on StackOverflow.

**Comment by alxhotel** [comment]
I don't think this is a "usage" question. The component should work as expected, and it's not.

I think this is an implementation issue.

**Comment by alxhotel** [comment]
That's not the point of this problem, but thanks anyway.
