### ISSUE TITLE
 Invalid prop `multiline` of type `string` supplied to `ReactTooltip`, expected `boolean`

### ISSUE THREAD

**Issue by tunecrew** [react-component/tooltip#133]
Getting this error in the Chrome console:

`Warning: Failed prop type: Invalid prop `multiline` of type `string` supplied to `ReactTooltip`, expected `boolean`.`

My code is:

`<ReactTooltip multiline='true'/>`

Don't always get it, and can't tie down exactly what triggers it.

react-tooltip still works (including multiline)

**Comment by zombieJ** [comment]
`<ReactTooltip multiline />`
