### ISSUE TITLE
Theme white and black

### ISSUE THREAD

**Issue by brandonsueur** [react-component/tooltip#139]
Hello,

it would be cool to propose an already predefined white and black theme !

example : 

```js
ReactDOM.render(
  <Tooltip theme="dark" placement="left" trigger={['click']} overlay={<span>tooltip</span>}>
    <a href="#">hover</a>
  </Tooltip>,
  container
);

// or

ReactDOM.render(
  <Tooltip theme="white" placement="left" trigger={['click']} overlay={<span>tooltip</span>}>
    <a href="#">hover</a>
  </Tooltip>,
  container
);
```

So, just invert the color and the background and add a little shadow when the theme and white.

see you !

**Comment by zombieJ** [comment]
You can use `prefixCls` to wrap the tooltip component to customize your own theme : )
