### ISSUE TITLE
placement是对象的时候，箭头定位有问题

### ISSUE THREAD

**Issue by shepherdwind** [react-component/tooltip#2]
当传入的placement是dom-align配置对象的时候，比如：

```
      placement: {
         points: ['bl', 'tl'],
         offset: [-10, -8]
      }
```

getPlacementCss返回的是`placement-[object object]`，然后箭头就没有了。

**Comment by shepherdwind** [comment]
感觉这个定位麻烦，如果这种自定义的需要定位的话.

**Comment by yiminghe** [comment]
现在 arrow 是 css 定位的
新增加个 arrowPlacement?

**Comment by shepherdwind** [comment]
主要是定位的情况太多了，那个pointer配置，arrow的位置都不一样。这个得想想怎么写，我实现了一个位置(['bl', 'tl'])的布局，不过这种组合情况太多了。如果没中单独配置，应该不可行的。

**Comment by shepherdwind** [comment]
或者这种形式http://spmjs.io/package/arale-tip，要有好一些

**Comment by yiminghe** [comment]
加个 arrowPosition?
