### ISSUE TITLE
Disabled button doesn't properly register for the hover trigger

### ISSUE THREAD

**Issue by longebane** [react-component/tooltip#200]
I have adjacent disabled buttons where I need to display a tooltip explaining why they are disabled. The mouseover trigger seems to work properly and opens the tooltip, but the the mouse leave does not work properly - the tooltip will not close. 
![image](https://user-images.githubusercontent.com/3925035/69093122-ad2f6c00-0a02-11ea-88e9-50505d9afd0b.png)

**Comment by Subalee** [comment]
+1

**Comment by michal-murawski** [comment]
I just noticed the same behaviour in my application.

**Comment by vivek-tikar** [comment]
+1

**Comment by afc163** [comment]
Duplicate of https://github.com/react-component/tooltip/issues/18
