### ISSUE TITLE
assets / bootstrap.css file is gone

### ISSUE THREAD

**Issue by Ryuurock** [react-component/tooltip#212]
it's in 4.0.0-alpha.3

**Comment by akshatmittal** [comment]
I'm honestly surprised the devs just decided to drop the css file from the package without thinking about how many projects will this change break. Considering this project does 3.4M downloads a month, this will make a lot of people unhappy.

I really hope this is a mistake. (The examples and demo code hasn't changed either, so I really hope this is an error).

**Comment by afc163** [comment]
Fixed in 4.0.3
