### ISSUE TITLE
Impossible to (programmatically) make the tooltip not transparent

### ISSUE THREAD

**Issue by fsoikin** [react-component/tooltip#215]
The problem is that `opacity` is always removed from `overlayStyle` in `rc-popup` code here: https://github.com/react-component/trigger/blob/858968c26585c7440ae948513045346c7b1eb682/src/Popup.tsx#L299-L304

Because of this, even if I specify `overStyle={{opacity: 1}}`, it has no effect, and the tooltip stays transparent.

## Repro

```
import Tooltip from 'rc-tooltip'

const App = () => 
    <Tooltip overlayStyle={{opacity: 1}} content="I'm still transparent!">
        Hover on me
    </Tooltip>
```

## Workaround
Fortunately, this can be (more or less) easily fixed by modifying the `rc-tooltip` class:

```
<style>
    .rc-tooltip { opacity: 1 !important }
</style>
```

**Comment by alionaSipchuk** [comment]
@fsoikin as i understand, you are incorrect define the Tooltip(and opacity can't fix your problem):
1) 'Tooltip' components don't accept text as child elements. Wrap text into span or etc. that create RaectElement as child.
2) Property 'content' does not exist on type 'IntrinsicAttributes & TooltipProps'. For these purpose you can use overlay property.

i hope i could help you
It will be work correct:
![image](https://user-images.githubusercontent.com/17640487/82892065-77da7c80-9f57-11ea-8b24-3421ac6ffb44.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/1bf99590625368246ee37fdb4c7b0de8f2aaa281/components/style/themes/default.less#L451

**Comment by fsoikin** [comment]
Those are just typos. The problem with opacity does exist. Please reopen the case.

**Comment by max-arias** [comment]
This is still an issue, I don't see a reason why you'd exclude a css property from being overriden?

**Comment by alisman** [comment]
It's b/c opacity is now used to hide the tooltip initially while tooltip is positioned/measured.   not sure what the solution is now.  this is a real problem.  because who wants transparent tooltip?

**Comment by Mi-Lan** [comment]
Hey guys easy fix for this is to move ReactTooltip component to be parent or grandparent of the place where tooltip will be applies check commit in our codebase how I fixed it! https://github.com/protofire/omen-exchange/pull/1925/commits/3d1013d7ba0c17bc6214fe8df7183e4bd3872776
