### ISSUE TITLE
Docs to get started are not entirely right

### ISSUE THREAD

**Issue by hackhat** [react-component/tooltip#22]
If you just follow the steps, then the component will have the class `rc-tooltip-hidden` but there is no CSS rule for this class. Therefore it will not hide and it will not position correctly.

Position should also be absolute, because relative increases the height of the page and is not positioned correctly.

In order to make it work properly you need to include the bootstrap.css file.

If you are using less use this:

    @import (inline) 'projectRoot/node_modules/rc-tooltip/assets/bootstrap.css';

**Comment by yiminghe** [comment]
yes. create your own css or use preset

**Comment by hackhat** [comment]
I think you should add this to the "get started" section instead of leaving users wondering why it doesn't work.

**Comment by tsuna** [comment]
+1

for those using webpack, you need to `npm install style-loader css-loader` and to add this to your webpack config:

```javascript
module.exports = {
  // ...
  module: {
    loaders: [
      // your JavaScript/JSX loader here (probably babel) ...
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader',
      }
    ]
  }
}
```

and then just `import 'rc-tooltip/assets/bootstrap.css';`
