### ISSUE TITLE
Tooltip is not triggered when child is component.

### ISSUE THREAD

**Issue by OurMajesty** [react-component/tooltip#224]
When child of RcTooltip is some component, then tooltip is not triggered.
BTW, Ant Design's Tooltip, using RcTooltip too, having the same problem.

CodeSandbox link to reproduce: [https://codesandbox.io/s/still-browser-hwdgm](https://codesandbox.io/s/still-browser-hwdgm)

**Comment by klamath** [comment]
Hi. @OurMajesty you should use all props from child component. 
I've fixed your example.
https://codesandbox.io/s/blazing-meadow-xbbi1?file=/index.js

**Comment by OurMajesty** [comment]
@klamath I don't see any differences in your example, did you forget to save changes?

**Comment by klamath** [comment]
Yeah )

**Comment by klamath** [comment]
`function Comp(props) {
  return <span {...props}>{props.children}</span>;
}`

**Comment by OurMajesty** [comment]
So there is onMouseEnter and onMouseLeave props, which should be forwarded to inner element.  
I wonder, should this be mentioned in docs.

**Comment by klamath** [comment]
There is other events as well. 
[Docs link](https://github.com/react-component/tooltip#note)

**Comment by OurMajesty** [comment]
Oh, I see, how I missed it.
