### ISSUE TITLE
4.2.3 marked as "latest"

### ISSUE THREAD

**Issue by deej-split** [react-component/tooltip#229]
It appears to me that when 4.2.3 was published, it got marked as the latest version of the package. Thus if someone starts a new repo and says `npm install rc-tooltip` they'll get 4.2.3 and not 5.0.1.  Was this deliberate?

**Comment by afc163** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/507615/97657175-2a34e380-1aa4-11eb-9768-15eb76d0adca.png">

Done.

**Comment by deej-split** [comment]
非常謝謝您！！
