### ISSUE TITLE
Add a doc/warning about passing down callbacks into custom components

### ISSUE THREAD

**Issue by hackhat** [react-component/tooltip#24]
Would be nice to add a warning for custom component saying that you need to pass down some callbacks to work.

    if (trigger.indexOf('click') !== -1) {
      newChildProps.onClick = createChainedFunction(this.onClick, childProps.onClick);
      newChildProps.onMouseDown = createChainedFunction(this.onMouseDown, childProps.onMouseDown);
      newChildProps.onTouchStart = createChainedFunction(this.onTouchStart, childProps.onTouchStart);
    }
    if (trigger.indexOf('hover') !== -1) {
      newChildProps.onMouseEnter = createChainedFunction(this.onMouseEnter, childProps.onMouseEnter);
      newChildProps.onMouseLeave = createChainedFunction(this.onMouseLeave, childProps.onMouseLeave);
    }
    if (trigger.indexOf('focus') !== -1) {
      newChildProps.onFocus = createChainedFunction(this.onFocus, childProps.onFocus);
      newChildProps.onBlur = createChainedFunction(this.onBlur, childProps.onBlur);
    }

**Comment by yiminghe** [comment]
wrap your custom component within a dom component is fine

**Comment by hackhat** [comment]
I know, maybe add this to the docs?

**Comment by yiminghe** [comment]
welcome pull request :)
