### ISSUE TITLE
Tooltip not showing up when attached to Bootstrap Modal element

### ISSUE THREAD

**Issue by bbguitar77** [react-component/tooltip#28]
I have a bootstrap modal with form buttons that I provide tooltips for ... however, the tooltips aren't showing up. I've tried increasing the z-index in the rc-bootstrap.css but that didn't fix the problem. Tooltip works fine in other non-modal parts of my application.

Anything else I should try?

**Comment by yiminghe** [comment]
try set overlayStyle prop to increase zIndex

can you provide a demo on github?

**Comment by stahlmanDesign** [comment]
Adding overlayStyle prop works:
```jsx
    <Tooltip
      prefixCls="rc-slider-tooltip"
      overlay={value}
      overlayStyle={{ zIndex: 1051 /* because modal is 1050 */ }}
      visible={dragging}
      placement="top"
      key={index}
    >
```
