### ISSUE TITLE
React 0.14 Compatibility

### ISSUE THREAD

**Issue by natorojr** [react-component/tooltip#29]
This project is not technically React 0.14 compatible since two of its dependencies are not: rc-align and rc-animate.

When using rc-tooltip w/ React 0.14, you'll get the following warning/error in the console:

> Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

I have create these PRs to update the dependencies:

rc-animate: https://github.com/react-component/animate/pull/4
rc-align: https://github.com/react-component/align/pull/4

**Comment by yiminghe** [comment]
fixed
