### ISSUE TITLE
当 placement 是方向时，无法设置 placement.offset

### ISSUE THREAD

**Issue by afc163** [react-component/tooltip#3]
https://github.com/react-component/tooltip/blob/dfd2650ea3c21262291eb6dad297d705b71e58f8/src/Tooltip.jsx#L106

需要用这个调整下浮层和 trigger 的距离。

**Comment by yiminghe** [comment]
ant-design 用样式实现不行么，这个应该是固定的

**Comment by afc163** [comment]
样式怎么实现，四个方向的。。

目前的默认距离靠的太近了。

**Comment by shepherdwind** [comment]
我也觉得放中间有点丑，一般都是黄金分割点的

**Comment by yiminghe** [comment]
比如距离远点

```
.rc-tooltip-placement-right > .rc-tooltip-arrow {
  top: 50%;
  left: 20px;
｝

.rc-tooltip-placement-right {
  margin-left: 27px;
  padding: 0 25px;
}
```

**Comment by yiminghe** [comment]
用 offset 的话要自定义样式了

http://react-component.github.io/tooltip/build/examples/points.html

**Comment by shepherdwind** [comment]
我觉得arale那种，7个位置的，是最实用的。周末有空了，我来搞下

**Comment by yiminghe** [comment]
ok, 提个 pr 看看

**Comment by afc163** [comment]
tooltip 四个方向就够用了。

popover 可能需要 7 个方向。
