### ISSUE TITLE
Allow me to change tooltip arrow color

### ISSUE THREAD

**Issue by culmor30** [react-component/tooltip#30]
It seems to be hard-coded to black in `/assets/bootstrap.less`, using different border-colors according to the tooltip's placement. Perhaps the arrow styling could be done somewhere in the javascript so I could pass in a hex color?

It's possible to work around it in the meantime, but I have to do these sorts of gymnastics:

```sass
.my-overlay-className {
    &.top {
        .rc-tooltip-arrow {
            border-top-color: palegoldenrod !important;
        }
    }
    &.left {
        .rc-tooltip-arrow {
            border-left-color: palegoldenrod !important;
        }
    }
    &.right {
        .rc-tooltip-arrow {
            border-right-color: palegoldenrod !important;
        }
    }
    &.bottom {
        .rc-tooltip-arrow {
            border-bottom-color: palegoldenrod !important;
        }
    }
}
```

**Comment by afc163** [comment]
It is too much for javascript.

**Comment by benjycui** [comment]
@culmor30 actually, you can edit `/assets/bootstrap.less`. For `Tooltip` is just a React component, you can use any style.

**Comment by yiminghe** [comment]
yes, please use overlayClassName to add your own style. javascript is fine.
