### ISSUE TITLE
index.md is not found

### ISSUE THREAD

**Issue by marina-marina** [react-component/tooltip#31]
Cannot look through examples. ```http://localhost:8007/examples/index.md``` is saying not found.

**Comment by yiminghe** [comment]
http://react-component.github.io/tooltip/

**Comment by marina-marina** [comment]
I'm sorry, I was not specific enough. Can't look through the examples locally when I install the repo.

**Comment by benjycui** [comment]
See: https://github.com/react-component/tooltip/pull/33
