### ISSUE TITLE
Setting tooltip container to the triggering element would not allow to click on the popup

### ISSUE THREAD

**Issue by ariesxje** [react-component/tooltip#34]
The plugin would append the popup to the DOM document if a container is not set.
We want the popup to move around with the triggering element, so we have to set the tooltip container.
````
<Tooltip
  trigger="click"
  getTooltipContainer={()=>document.getElementById('tooltip-container')}
  overlay={
    <div>
      <a href="www.google.com">a link</a>
    </div>
  }
  >
  <div id="tooltip-container">click me<div>
</Tooltip>
````

Now the tooltip would go wherever the "click me" button goes.
But, the issue is, when clicking on the tooltip, the event is considered as clicking on the parent element:
````
<div id="tooltip-container">click me</div>
````
which closes the tooltip!!!

What is worse, we couldn't even click on the link inside the tooltip since this line of code:
````
event.preventDefault();
````
inside the onClick function of the Trigger.js file, which is a dependency file of this plugin.

I don't think it should be
````
event.preventDefault();
````
Instead, it should be
````
event.stopPropagation();
````

If we change that, clicking on the link would work, but the tooltip would close immediately.

I think the problem is, clicking on the tooltip, even the tooltip is a child element of the "click me" button, should not be treated as clicking on the "click me" button.
Can you change the trigger event, so that when we set the tooltip container to the triggering element, clicking on the tooltip would not close itself?

I have tried another method that manually handles the "visible" attribute, but then I lose the ability to close it by clicking on other elements. Also, the
````
event.preventDefault();
````
still prevents the user clicking on anything inside the tooltip.

**Comment by ariesxje** [comment]
Actually I have accomplished that by putting the popup into a container that is above the "click me" button, which is also positionally relative.
But anyway, it'd be cool if the popup can be attached straightly under the triggering button, without making use of other element that is not supposed to be involved.

**Comment by yiminghe** [comment]
It is not recommended to render popup inside tooltip, you can encapsulate to create custom Tooltip component.

```
<span style='position:relative'>
<Tooltip getTooltipContainer={...}>
</Tooltip>
<span id='container'></span>
</span>
```
