### ISSUE TITLE
`Tooltip` crashes

### ISSUE THREAD

**Issue by benjycui** [react-component/tooltip#35]
See: https://github.com/react-component/slider/issues/52

**Comment by benjycui** [comment]
`isMounted` is going to be deprecated https://github.com/facebook/react/issues/5465

**Comment by yiminghe** [comment]
和这个没关系，react 0.14.1 修复的

https://github.com/facebook/react/pull/5125

**Comment by benjycui** [comment]
嗯，不过 `isMounted` 还是要去掉吧？已经计划 deprecated 了。

**Comment by yiminghe** [comment]
还没有结论，去掉后反而自己要做很多事情，不合理

**Comment by vdv73rus** [comment]
Hi! I am using react 0.14.3 & rc-tooltip 3.2.0, but on mouseleave I had an error:
`Uncaught TypeError: this.isMounted is not a function`
