### ISSUE TITLE
Tooltip with React 18 and *without* StrictMode cause browser crash/freeze

### ISSUE THREAD

**Issue by ChrisLuYi-Aon** [react-component/tooltip#351]
Same as the issue [here](https://github.com/ant-design/ant-design/issues/34890), seems it's already been fixed, can we have a release on the rc-tooltip component for this fix?

**Comment by antollika** [comment]
Have the same issue.
But
The most interesting thing is that I have M1 max and I do not have any issues. But my teammate with core i7 has it (macOs and windows) :)

**Comment by antollika** [comment]
@ChrisLuYi-Aon try install 
"rc-trigger": "^5.3.1"

It helped me

**Comment by ChrisLuYi-Aon** [comment]
> @ChrisLuYi-Aon try install "rc-trigger": "^5.3.1"
> 
> It helped me

Thanks, @antollika, yes I did it for my project, and it works! Hope they also update the tooltip package soon

**Comment by antollika** [comment]
@ChrisLuYi-Aon 
I've create PR https://github.com/react-component/tooltip/pull/360
Lets wait :)

**Comment by yoni-salt** [comment]
Have the same issue, ive installed "rc-trigger" its better but not stable, if i have several elements that has a tooltip and I run with the mouse between them to test it, it will crash the browser(latest chrome)
