### ISSUE TITLE
Tooltip position when scrolling a container with overflow: auto/scroll

### ISSUE THREAD

**Issue by joaovpmamede** [react-component/tooltip#41]
Not sure if it's because the Tooltip Component is being rendered in `body` instead of inside another DOM node but when scrolling a div that has `overflow: auto/scroll`, the tooltip won't "stick" to its container.

In the [simple example](http://react-component.github.io/tooltip/examples/simple.html) you can scroll and the tooltip is stuck to the container.

**Comment by yiminghe** [comment]
use getTooltipContainer to render inside specified container

**Comment by joaovpmamede** [comment]
Ok, thanks. 
Will try that as soon as possible.

**Comment by ongbenny** [comment]
I have tried this but it does not work as the tooltip stays in place while scrolling. Could you provide an example?

**Comment by mikemunsie** [comment]
I just ran into this issue and I used getTooltipContainer to return the container I wanted the tooltip to live in. 

```
<Tooltip
  ...
  getTooltipContainer={() => document.querySelector(".myContainerIWantThisIn")}
>
...
</Tooltip>
```

The documentation is a bit unclear and doesn't specify that it will actually move the tooltip into the specified container. Might just add in a PR to help out.
