### ISSUE TITLE
Explicit setVisible for tooltip

### ISSUE THREAD

**Issue by mjrussell** [react-component/tooltip#43]
When using the trigger (i.e. click) there is no way to close the popover programatically. I know that I could use the `visible` prop but I'd rather leave it as an uncontrolled component or else have to implement the click trigger myself. It would be nice if `<Tooltip>` exposed a [setPopupVisible](https://github.com/react-component/trigger/blob/master/src/Trigger.jsx#L274) on the component so you don't have to access the `trigger` ref inside it.

This could simply be:
```js
setPopupVisible(popupVisible) {
  this.refs.trigger.setPopupVisible(popupVisible)
}

```

**Comment by yiminghe** [comment]
you do not need to implement the click trigger yourself, just listen
```
onVisibleChange(visible) {
  this.setState({visible})
}

render(){
 <Tooltip visible={this.state.visible} onVisibleChange={onVisibleChange}>
}
```

So use visible prop.

**Comment by mjrussell** [comment]
@yiminghe but then you don't get the clickaway trigger (i.e. closing when clicking outside the dropdown) right? And have to implement it yourself? Thats not impossible but not ideal

**Comment by yiminghe** [comment]
you will get the clickaway trigger (i.e. closing when clicking outside the dropdown), it will trigger onVisibleChange(false)

try first

**Comment by mjrussell** [comment]
Ah ok sorry, I thought I had tried that but your suggestion works. Thanks!
