### ISSUE TITLE
yarn install error because some strange folders...

### ISSUE THREAD

**Issue by dbalas** [react-component/tooltip#457]
Hello,

In the latest release, there are strange files in the /dist folder that do not match the repo, and these are causing installations to fail with yarn (I did not try npm).

<img width="977" alt="image" src="https://github.com/react-component/tooltip/assets/1343562/2fd9a0ec-b309-46c1-bf47-5a2c03b4f1f2">

**Comment by yoyo837** [comment]
Seem this is a path name that is not Windows compatible

**Comment by yoyo837** [comment]
https://github.com/react-component/tooltip/releases/tag/v6.1.1
