### ISSUE TITLE
Warnings.

### ISSUE THREAD

**Issue by satazor** [react-component/tooltip#47]
Hello, I get a few warnings when using this component:

```
warning.js:44 Warning: Unknown prop `visible` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by LazyRenderBox)
    in LazyRenderBox (created by PopupInner)
    in div (created by PopupInner)
    in PopupInner (created by Popup)
    in Align (created by Popup)
    in AnimateChild (created by Animate)
    in Animate (created by Popup)
    in div (created by Popup)
    in Popup

**Comment by gabrielenosso** [comment]
I also get a warning:
 Invalid prop `popup` supplied to `Trigger`

These are new warnings that the new React added in its last version (15.2.x).
The warning is explained there: https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by gabrielenosso** [comment]
Any news there?
Is not so comfortable to get a warning everytime :)

**Comment by afc163** [comment]
It should have been fixed in https://github.com/react-component/trigger/pull/19
