### ISSUE TITLE
onlyChild must be passed a children with exactly one child

### ISSUE THREAD

**Issue by darrencrossley** [react-component/tooltip#50]
Occurs only on the latest version, downgrading to 3.3.5 solves this problem so guessing something got published prematurely?

Tested on react 15.1.0.

**Comment by yiminghe** [comment]
master examples and tests are ok?

need a demo, gh-pages prefered

**Comment by vaclav-zeman** [comment]
+1

I've got the same problem, running on react 15.3.0, and also downgrading to 3.3.5 solves it.

**Comment by benjycui** [comment]
Close for no re-producible demo.

If someone meet this issue, please provide a re-producible online demo, thanks.

**Comment by abraham-chan** [comment]
In React 15.3.1 the message changed to `React.Children.only expected to receive a single React element child.` 
This helped me figure out that it's a problem with passing non-Element children.  

For example:
`<Tooltip>{ "hello" }</Tooltip>` => Error
`<Tooltip><span>{ "hello" }</span></Tooltip>` => No error

Tried on 3.4.9 and react 15.3.2

**Comment by Kadrian** [comment]
Just encountered a similar issue React 16 as well, where it doesn't work if you pass a stateless functional component into `Tooltip`, even though that component only renders a span.
