### ISSUE TITLE
Cannot use custom components as targets

### ISSUE THREAD

**Issue by witwit** [react-component/tooltip#51]
Tooltip works like a charm with html5 elements like `<div>` or `<span>`, however if I put a custom element inside, the tooltip does not appear.

example:

```
// my custom component:
function Tester ({children}) {
    return (
        <div style={{color: 'red'}}>
            {children}
        </div>
    )
}
```

```
// works:
<Tooltip content={<div>hello</div>} >
        <div style={{color: 'green'}}>
            Hover over me!
        </div>
</Tooltip>

// does NOT work:
<Tooltip content={<div>hello</div>} >
        <Tester>
            Hover over me!
        </Tester>
</Tooltip>
```

Or is there something I am missing?

Seems to be a triggering issue, because setting parameters to visible or defaultVisible does show the tooltip on both cases.

**Comment by witwit** [comment]
I seem to have found a solution for this. The custom component needs to pass all props to the first child element, then it works as expected:

```
function Tester (props) {
    const { children, ...otherProps } = props
    return (
        <div style={{color: 'red'}} {...otherProps}>
            {children}
        </div>
    )
}
```

**Comment by chiefGui** [comment]
Another solution that doesn't hurt is wrapping your custom component:

```jsx
<Tooltip content={<div>hello</div>}>
  <div>
    <Tester>
      Hover over me!
    </Tester>
  </div>
</Tooltip>
```

But still an issue.

**Comment by yesmeck** [comment]
`Tooltip` requires children to response `click`, `mouseEnter`, `mouseHover` and `focus` events.

**Comment by benjycui** [comment]
@yesmeck may be we should update README.md?
