### ISSUE TITLE
Tooltip Position is wrong when the tooltip is bigger

### ISSUE THREAD

**Issue by oizie** [react-component/tooltip#53]
I am having issues with the tooltip and it seems it's a specific implementation in the library to position in a visible area to the user.
However in my case I really don't mind that part of the tooltip is not visible and the user would need to scroll to see the entire content if it doesn't fit.

I am using getTooltipContainer to display the tooltip in that specific span. If it doesn't fit in the screen I don't want to change the position to something else. 

Here is a small video showing this behaviour:
[http://screencast.com/t/t2yLeNOmam](http://screencast.com/t/t2yLeNOmam)

**Comment by oizie** [comment]
Here is my code: 
`<span style={{position: "relative"}}>
                    <Tooltip placement="bottomLeft"
                                    overlayClassName="overlay-mega-search"
                                    getTooltipContainer={()=>document.getElementById("container_" + this.props.uniqueId)}
                                    trigger={['click']}
                                    destroyTooltipOnHide={true}
                                    transitionName="rc-tooltip-mega-search"
                                    visible={this.state.visible}
                                    onVisibleChange={this.onVisibleChange.bind(this)}
                                    overlay={<span>{content}</span>}>
                        <div className={"dropdown "  + (this.state.visible ? "active" : (this.state.showError ? "error" : ""))}>
                                <div className="trigger">
                                    <span className="label">{this.props.title}</span>
                                    <input type="text"
                                        ref="searchText"
                                        placeholder={this.props.placeholder}
                                        onKeyPress={(e) => this.checkKey(e.charCode)}
                                        onChange={(e) => this.searchByText((e.target as any).value)}
                                        className="value"
                                        value={this.props.searchText} />
                                </div>
                        </div>
                    </Tooltip>
                    <span id={"container_" + this.props.uniqueId} />
                </span>`

**Comment by satazor** [comment]
I'm having this same issue on npms.io, is this solvable?

**Comment by rohanBagchi** [comment]
For those who have come in here with similar issue, this is how I solved mine:
I found `rc-tooltip` faced this issue when the overlay content is an `img`.
Even if the said image has a fixed height / width.
I wrapped my image with a fixed size `div` and that seemed to make the issue go away.
