### ISSUE TITLE
当 trigger 同时包含 click 和 focus 时可能点击后出现问题

### ISSUE THREAD

**Issue by riophae** [react-component/tooltip#6]
```javascript
<Tooltip
  trigger={['click', 'focus']}
  alignment='top'
  overlay={<span>Hey!</span>}
>
  <a href='#'>Click me</a>
</Tooltip>
```

例如上面这样，或者直接在 demo 中同时选中 `click` 和 `focus` 这两个 trigger，当第一次点击 trigger 链接时，会看到气泡弹出后立刻自动收回了。可能是因为 `click` 和 `focus` 两个事件同时触发导致。

**Comment by yiminghe** [comment]
已经可以了  http://react-component.github.io/tooltip/examples/simple.html

**Comment by riophae** [comment]
谢谢！

**Comment by riophae** [comment]
刚才又测试了一下，连续点击发现有时还是会意外消失

**Comment by yiminghe** [comment]
浏览器，版本？ 我重现不了，可以尝试自己解决下提个 pull request

**Comment by riophae** [comment]
Chrome 44.0.2403.61 beta
OS X 10.10.4
我研究下

**Comment by yiminghe** [comment]
嗯，没测试过 chrome beta 版本

2015-07-07 19:37 GMT+08:00 Fangzhou Li <notifications@github.com>:
