### ISSUE TITLE
Programmatically close tooltip

### ISSUE THREAD

**Issue by jmcrthrs** [react-component/tooltip#64]
My tooltip displays a button that launches a modal.

When the button is clicked, I would like to close the Tooltip.

However there doesn't appear to be anything in the API to manually close the Tooltip. 

Has anyone needed to do this?

Or perhaps I actually need a different component i.e. a Popover component.

**Comment by benjycui** [comment]
https://github.com/react-component/tooltip

![image](https://cloud.githubusercontent.com/assets/3580607/20612111/6ca7d516-b2f1-11e6-8987-bf58d01511d1.png)

**Comment by jmcrthrs** [comment]
Ha, I had no idea why I thought visible was read only. Thanks.
