### ISSUE TITLE
tooltip能不能消失

### ISSUE THREAD

**Issue by longang520** [react-component/tooltip#67]
鼠标移除tooltip后就消失,不能 在tooltip还不消失,影响 点击其他的东西.

**Comment by benjycui** [comment]
语言混乱。

**Comment by longang520** [comment]
不好意思.
需求:在显示tooltip的时候,鼠标移动到tooltip也会消失.
现状:在显示tooltip的时候,鼠标可以移动到tooltip上,变选择tooltip的信息.

**Comment by benjycui** [comment]
通过 `visible` 属性控制。

**Comment by afc163** [comment]
`mouseLeaveDelay={0}`
