### ISSUE TITLE
Tooltip always follows the bottom of the page

### ISSUE THREAD

**Issue by ImadBoumzaoued** [react-component/tooltip#68]
The Tooltip always sticks to the bottom of the page if it's element is not visible:
<img width="360" alt="screen shot 2017-01-06 at 16 19 45" src="https://cloud.githubusercontent.com/assets/1586936/21724389/0ba6f9c0-d42c-11e6-9823-7f718af15542.png">
<img width="278" alt="screen shot 2017-01-06 at 16 20 02 1" src="https://cloud.githubusercontent.com/assets/1586936/21724390/0ba79830-d42c-11e6-9394-4adb388ce875.png">

**Comment by Elliot128** [comment]
I've ran into this issue now that rc-slider depends on rc-tooltip for custom tooltips... Still no way around this?

**Comment by ImadBoumzaoued** [comment]
@Elliot128 nah man I kinda forgot about it as I'm waiting for a fix, because it was tagged low on the project priorities.

**Comment by benjycui** [comment]
Fixed in https://github.com/yiminghe/dom-align/pull/11

Waiting for next patch version.

**Comment by ImadBoumzaoued** [comment]
@benjycui thanks man, appreciate it
