### ISSUE TITLE
Re-anchor/position Tooltip?

### ISSUE THREAD

**Issue by stewartcelani** [react-component/tooltip#69]
Hello there! One big use for ReactTooltip in a project I'm working on is to mouse over urls and have a tooltip show a description of the site via an embedly call. When the embedly call completes it renders a small picture + description of the website and messes up the position of the tooltip. As soon as you move the mouse inside the element the tooltip will right itself.

Here's whats going on: 
![reacttooltip](https://cloud.githubusercontent.com/assets/391792/21878013/1df711de-d8df-11e6-9b1c-dac3099531ab.gif)

I have a callback when the embed loads so I've tried messing around by triggering a custom 'updatetooltip' global event that I set up a listener for from 'bindListener' in index.js. It receives the events fine (console.logs working as expected etc) but calling either updateTooltip or updatePosition doesn't seem to do anything (well updatePosition throws a cannot read property 'currentTarget' of undefined). Also tried calling hideTooltip and then showTooltip but the show doesn't go through. ReactTooltip.rebuild() neither. Bit stumped.

Any ideas on how I could go about solving this would be hugely appreciated. Thanks for all your work on this library!

**Comment by benjycui** [comment]
Use `visible` to show Tooltip after content loaded, see: https://github.com/react-component/tooltip#props

**Comment by stewartcelani** [comment]
Just realised I posted this to the wrong place. And boy do I feel stupid. 

Sorry. =P
