### ISSUE TITLE
destroyTooltipOnHide is not supported by rc-trigger

### ISSUE THREAD

**Issue by kamilmielnikcodete** [react-component/tooltip#75]
`destroyTooltipOnHide` prop is simply passed down to `rc-trigger` component, but it's not supported by `rc-trigger`.

Please remove it to avoid confusion or support it somehow (the latter would be preferred).

**Comment by benjycui** [comment]
I think it should work after reading the source code.

If you had met problem, please provide a re-producible online demo, thanks.
