### ISSUE TITLE
Messed up arrow after window resize

### ISSUE THREAD

**Issue by eav** [react-component/tooltip#79]
You can reproduce the issue at http://react-component.github.io/tooltip/examples/simple.html, just set placement to bottomRight, then decrease the height of the browser until popup flip, then increase the height again. Here is the screenshot:
![screenshot from 2017-05-11 21-55-51](https://cloud.githubusercontent.com/assets/249929/25966930/284d639a-3695-11e7-9592-bd4a2caa3806.png)

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`
