### ISSUE TITLE
Various event to show and hide tooltip

### ISSUE THREAD

**Issue by DonRai** [react-component/tooltip#80]
It's possible show tooltip on click and hide tooltip on mouse leave?
For example:
show="click"
close="hover"

**Comment by benjycui** [comment]
Why? It will be confusing to users.

**Comment by paranoidjk** [comment]
looks weird... I can not image this use case

**Comment by afc163** [comment]
Try

```jsx
<Tooltip showAction={['click']} hideAction={['hover']} />
```

**Comment by gndelia** [comment]
> Try
> 
> ```js
> <Tooltip showAction={['click']} hideAction={['hover']} />
> ```

those props do not exist - only `trigger` does (or the TS types are wrong)
