### ISSUE TITLE
Tooltip not hiding on mouse leave on button disabled

### ISSUE THREAD

**Issue by manuel-bitcraft** [react-component/tooltip#81]
The tooltip appears correctly hovering in, however it does not disappear when hovering out.

`<Tooltip placement="top" overlay="Cannot delete">
     <button disabled="disabled">Remove</button>
 </Tooltip>`

**Comment by paranoidjk** [comment]
a reproducible demo, please

**Comment by afc163** [comment]
https://github.com/react-component/tooltip/issues/18

**Comment by manuel-bitcraft** [comment]
@paranoidjk see my first comment
@afc163 Thanks, I didn't check the closed bugs.

In my case, I'm using boostrap css, so instead of setting the button property "disabled", I just added a class "disabled" to the button.

Not the same thing, but gets the job done for me.

Thanks
