### ISSUE TITLE
How about afterVisibleChange?

### ISSUE THREAD

**Issue by adaptunit** [react-component/tooltip#91]
Hi

I see a callback 
"afterVisibleChange: PropTypes.func"

but it is not used on <Trigger /> definition
why?

please add it to code 
it will be convenient
thanks a lot

**Comment by benjycui** [comment]
Yep, we make a mistake. We should pass it to [`rc-trigger[afterPopupVisibleChange]`](https://github.com/react-component/trigger/blob/db4cb7117c52054d6cfec42859dee0c73c3fc31a/src/index.js#L34)

**Comment by benjycui** [comment]
Could you PR to fix this? @adaptunit

**Comment by benjycui** [comment]
3.4.7
