### ISSUE TITLE
Ignore tooltip when hiding on `trigger={['hover']}`

### ISSUE THREAD

**Issue by ajbeaven** [react-component/tooltip#92]
It appears that if the cursor leaves an element, it does not hide if the cursor remains over the tooltip itself. By way of example, I would like to avoid the following situation:

![image](https://user-images.githubusercontent.com/657201/27937312-3a28d846-630a-11e7-8d75-42addd0684d1.png)
```
<Tooltip overlay="Edit">
    {editButton}
</Tooltip>
```

And rather have it ignore the tooltip when calculating when to hide. Considering

**Comment by benjycui** [comment]
It's by design.. You can control this by `visible`

**Comment by ajbeaven** [comment]
Ok, then I suppose this should be considered a request for adding the option. I can understand this being the default behaviour for rc-trigger but IMO, considering the typical use case, it doesn't make sense for a tooltip.

**Comment by afc163** [comment]
Try `mouseLeaveDelay={0}`

**Comment by smhatre59** [comment]
mouseLeaveDelay={0} does the task of hiding tooltip immediately
