### ISSUE TITLE
Tooltip 在第一次渲染到 dom 上时位置错误

### ISSUE THREAD

**Issue by elowes** [react-component/tooltip#98]
container 底部空间不足时，Tooltip 应该自动调整位置，但是如果这个 Tooltip 没有触发过，那么第一次它出现的位置是错误的。但是第二次及以后再次触发时，它的位置就能够自适应了。当然如果把 destroyTooltipOnHide 设置为 true，那就每次位置都是不对的了。

**Comment by elowes** [comment]
![default](https://user-images.githubusercontent.com/8766034/29992758-da502ef8-8fd5-11e7-9f62-172ccc5b6c54.gif)

**Comment by afc163** [comment]
I believe it is been fixed in https://github.com/react-component/trigger/issues/41, If not, could you provider a reproducible demo?

**Comment by elowes** [comment]
confirmed this bug caused by I use [react-swipeable-views](https://github.com/oliviertassinari/react-swipeable-views).
